### ISSUE TITLE
String: "title_cancel_payment"

### ISSUE THREAD

**Issue by Kolyall** [ITECOMMPAY/paymentpage-sdk-android-ui#1]
![Screenshot_20221223_122150_emulator-5554](https://user-images.githubusercontent.com/3495165/209309184-8ab74cd6-3e9c-49fe-a07d-07dab0d664dc.png)

**Comment by Kolyall** [comment]
com.ecommpay:msdk-ui:2.1.1

**Comment by AlexeyKhrameev** [comment]
you need added string override "title_cancel_payment" at project settings
